spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
server.port=${PORT:8080}
hibernate.discriminator.ignore_explicit_for_joined=true
