spring.profiles.active=dev
spring.main.allow-bean-definition-overriding=true
server.port=${PORT:8080}
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
spring.web.resources.cache.period=0
spring.web.resources.cache.use-last-modified=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
