spring.profiles.active=prod
server.port=${PORT:8080}
spring.http.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.web.resources.cache.period=0
spring.web.resources.cache.use-last-modified=false