spring.datasource.url=jdbc:postgresql://localhost:5432/sokker_db
spring.datasource.username=sokker_user
spring.datasource.password=stojke
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
